set -e
set -x

#
# Remove files generated by `cmake .` and `cmake --build .`
#
rm -rf ./.qt/
rm -rf ./learning__qt_file_explorer_autogen/
rm -rf ./CMakeFiles
rm -f ./cmake_install.cmake
rm -f ./CMakeCache.txt
rm -f ./install_manifest.txt
rm -f ./learning__qt_file_explorer
rm -f ./Makefile

#
# Remove files generated by CLion's CMake support
#
rm -rf ./cmake-build-debug/
