set -e
set -x

#
# Remove files generated by `run_debug.sh`
#

rm -rf ./build_debug/

#
# Remove files generated by `run_release.sh`
#

rm -rf ./build_release/

#
# Remove files generated by CLion's CMake support
#

# the default build location if not override in personal project settings
rm -rf ./cmake-build-debug/
