set -e
set -x

#
# Remove files generated by `build_and_run.sh`
#

rm -rf ./build/

#
# Remove files generated by CLion's CMake support
#

# the default build location if not override in personal project settings
rm -rf ./cmake-build-debug/
